//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.RecipeIngredientJoins = new HashSet<RecipeIngredientJoin>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public Nullable<bool> IsVegetarian { get; set; }
        public Nullable<int> IsGlutenFree { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> CookTime { get; set; }
        public Nullable<int> RecipeTypeID { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual RecipeType RecipeType { get; set; }
        public virtual ICollection<RecipeIngredientJoin> RecipeIngredientJoins { get; set; }
    }
}
