//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredientJoin
    {
        public int RecipeID { get; set; }
        public int IngredientID { get; set; }
        public decimal Measurement { get; set; }
        public int MeasurementTypeID { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual MeasurementType MeasurementType { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
