//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeType
    {
        public RecipeType()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int RecipeGuideID { get; set; }
    
        public virtual ICollection<Recipe> Recipes { get; set; }
        public virtual RecipeGuide RecipeGuide { get; set; }
    }
}
